# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               EuroMoonMars
description:         EuroMoonMars
url:                 http://lanyon.getpoole.com
tagline:             An ILEWG Initiative
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              EuroMoonMars
  url:               https://euromoonmars.space
  email:             web@euromoonmars.space

# Custom vars
version:             1.0.0

# Portfolio
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
